version: 2
workflows:
  version: 2
  all:
    jobs:
      - node-latest:
          filters:
            tags:
              ignore: /.*/
      - node11:
          requires:
            - node-latest
      - node10:
          requires:
            - node-latest
      # - node8:
      #     requires:
      #       - node-latest
      - release:
          context: publish
          filters:
            branches:
              only: master
          requires:
            - node-latest
            - node11
            - node10
            # - node8
jobs:
  local:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: yarn verify
  node-latest:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          name: Restore node_modules cache
          key: node_modules-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: |
            if [ ! -d node_modules ]; then
              yarn
            fi
      - save_cache:
          name: Save node modules cache
          key: node_modules-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: yarn commitlint-circle
      - run: yarn lint
      - run: yarn build
      - run: yarn depcheck
      - run: yarn coverage --maxWorkers=2
      - store_test_results:
          path: .reports/junit
      - run: yarn bundle
      - persist_to_workspace:
          root: '.'
          paths:
            - node_modules
            - .tsbuildinfo
            - ./packages/*/dist/*
            - ./packages/*/lib/*
            - ./packages/*/libm/*
  node11:
    docker:
      - image: 'circleci/node:11'
    steps:
      - checkout
      - attach_workspace:
          at: '.'
      - run: yarn coverage --maxWorkers=2
      - store_test_results:
          path: .reports/junit
  node10:
    docker:
      - image: 'circleci/node:10'
    steps:
      - checkout
      - attach_workspace:
          at: '.'
      - run: yarn coverage --maxWorkers=2
      - run: npx codecov
      - store_test_results:
          path: .reports/junit
  node9:
    docker:
      - image: 'circleci/node:9'
    steps:
      - checkout
      - attach_workspace:
          at: '.'
      - run: yarn coverage --maxWorkers=2
      - store_test_results:
          path: .reports/junit
  node8:
    docker:
      - image: 'circleci/node:8'
    steps:
      - checkout
      - attach_workspace:
          at: '.'
      - run: yarn coverage --maxWorkers=2
      - store_test_results:
          path: .reports/junit
  release:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - attach_workspace:
          at: '.'
      - run: git config user.email $GIT_CONFIG_EMAIL
      - run: git config user.name $GIT_CONFIG_NAME
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run: yarn publish:ci
