export type Color = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7
export const BLACK = 0
export const RED = 1
export const GREEN = 2
export const YELLOW = 3
export const BLUE = 4
export const MAGENTA = 5
export const CYAN = 6
export const WHITE = 7
export const BRIGHT = 1
export const UNDERSCORE = 4
export const FOREGROUND = 30
export const BACKGROUND = 40
