name: release
on:
  push:
    branches: [main]

jobs:
  code:
    uses: unional/.github/.github/workflows/pnpm-verify.yml@main

  release:
    uses: unional/.github/.github/workflows/pnpm-release-changeset.yml@main
    needs: code
    secrets: inherit

  # TODO: do not run this when release creates PR only
  docgen:
    uses: unional/.github/.github/workflows/pnpm-docs.yml@main
    needs: release
