ignores:
  - '@repobuddy/jest'
  - '@size-limit/preset-small-lib'
  - '@types/jest'
  - '@types/node'
  - '@typescript-eslint/eslint-plugin'
  - '@typescript-eslint/parser'
  - compression-webpack-plugin
  - eslint-config-prettier
  - eslint-plugin-harmony
  - jest-*
  - param-case
  - pascal-case
  - size-limit
  - ts-jest
  - ts-loader
  - tslib
  - webpack-cli
